### ISSUE TITLE
commands should always work if --year is given

### ISSUE THREAD

**Issue by krisalyssa** [jakzo/aoc#6]
Okay, maybe not _always_. But I should be able to work on previous years when the current year's AoC is not active.

For example, today (2021-11-29) when I run `aoc start rust -y 2020` I get `Error: Advent of Code has not started yet` instead of initializing the current directory for the 2020 puzzles using the Rust templates.

Or is `start` not the correct command here? For that matter, it's not clear that there actually _is_ a way to download input and copy templates for past years. Maybe that's out of scope for this tool at this time?

**Comment by jakzo** [comment]
The `start` command requires a day parameter because the day is included in the generated template files. Adding `-d 1` should make the command work (change the number for different day). If the day is not provided it defaults to the current day (which doesn't make sense because AoC hasn't started yet, hence the message). The error messages could definitely be clearer though. I might make an issue to fix that.

**Comment by jakzo** [comment]
I've updated it to default to day 1 when the year is not set to the current year so you shouldn't get this error anymore.
