### ISSUE TITLE
Local template override

### ISSUE THREAD

**Issue by vegar** [jakzo/aoc#7]
Thank you for a great tool! Tried a couple of aoc cli's, and this is the one I've settled for :-D

Would it be possible to allow for local template overrides? 

If I keep a `templates` folder in the directory that I run `aoc` in, it should look for the language template there first. 
This would allow me to easily experiment and develop my template from day to day.
It would also allow for separate templates for each year.

**Comment by jakzo** [comment]
I'm glad you like it. 🙂  I definitely agree it should have local template overrides, but I wasn't sure how to implement them because the dev loop of some languages require logic to work (eg. compiled languages should compile to a temp directory and run the binary, linux and windows use different style paths, etc). I see two options:

1. When `aoc start LANG` is run, search for a local `templates/LANG/commands.js` file which contains the dev loop commands and the rest of the files in the directory are the template files. Requires everyone to use JS though. 🙃 
2. Same but instead of `commands.js` make it a text file of hardcoded commands. Template variables like `{{TEMP_DIR}}` will be replaced before the command is run.

Now that I think about it, cross-platform compatibility shouldn't be an issue for local templates so I don't think there's any need for JS now. I guess that's probably what I'd go with. If you have any other ideas I'm happy to hear them. 🙂

**Comment by jakzo** [comment]
I implemented it. See the readme for how to use it. 🙂

**Comment by vegar** [comment]
Great! Thanks. I'll test it out.
